# Generated by Django 4.2.2 on 2023-06-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='autor',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='blog',
            name='contenido',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='blog',
            name='titulo',
            field=models.CharField(default='', max_length=100),
        ),
    ]
